// Generated by @wagmi/cli@0.1.15 on 4/12/2023 at 1:14:55 PM
import {
  getContract,
  GetContractArgs,
  readContract,
  ReadContractConfig,
  writeContract,
  WriteContractMode,
  WriteContractArgs,
  WriteContractPreparedArgs,
  WriteContractUnpreparedArgs,
  prepareWriteContract,
  PrepareWriteContractConfig,
} from '@wagmi/core'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Counter
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0xfC5F404bEC816C6DC4F1ef4370C96bc5d0c561A9)
 */
export const counterABI = [
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'decrement',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getCurrentNumber',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'increment',
    outputs: [],
  },
] as const

/**
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0xfC5F404bEC816C6DC4F1ef4370C96bc5d0c561A9)
 */
export const counterAddress = {
  5: '0xfC5F404bEC816C6DC4F1ef4370C96bc5d0c561A9',
} as const

/**
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0xfC5F404bEC816C6DC4F1ef4370C96bc5d0c561A9)
 */
export const counterConfig = {
  address: counterAddress,
  abi: counterABI,
} as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Core
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link getContract}__ with `abi` set to __{@link counterABI}__.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0xfC5F404bEC816C6DC4F1ef4370C96bc5d0c561A9)
 */
export function getCounter(
  config: Omit<GetContractArgs, 'abi' | 'address'> & {
    chainId?: keyof typeof counterAddress
  },
) {
  return getContract({ abi: counterABI, address: counterAddress[5], ...config })
}

/**
 * Wraps __{@link readContract}__ with `abi` set to __{@link counterABI}__.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0xfC5F404bEC816C6DC4F1ef4370C96bc5d0c561A9)
 */
export function readCounter<
  TAbi extends readonly unknown[] = typeof counterABI,
  TFunctionName extends string = string,
>(
  config: Omit<ReadContractConfig<TAbi, TFunctionName>, 'abi' | 'address'> & {
    chainId?: keyof typeof counterAddress
  },
) {
  return readContract({
    abi: counterABI,
    address: counterAddress[5],
    ...config,
  } as unknown as ReadContractConfig<TAbi, TFunctionName>)
}

/**
 * Wraps __{@link writeContract}__ with `abi` set to __{@link counterABI}__.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0xfC5F404bEC816C6DC4F1ef4370C96bc5d0c561A9)
 */
export function writeCounter<
  TFunctionName extends string,
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof counterAddress,
>(
  config:
    | (Omit<
        WriteContractPreparedArgs<typeof counterABI, TFunctionName>,
        'abi' | 'address'
      > & {
        mode: TMode
        chainId?: TMode extends 'prepared'
          ? TChainId
          : keyof typeof counterAddress
      })
    | (Omit<
        WriteContractUnpreparedArgs<typeof counterABI, TFunctionName>,
        'abi' | 'address'
      > & {
        mode: TMode
        chainId?: TMode extends 'prepared'
          ? TChainId
          : keyof typeof counterAddress
      }),
) {
  return writeContract({
    abi: counterABI,
    address: counterAddress[5],
    ...config,
  } as WriteContractArgs<typeof counterABI, TFunctionName>)
}

/**
 * Wraps __{@link prepareWriteContract}__ with `abi` set to __{@link counterABI}__.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0xfC5F404bEC816C6DC4F1ef4370C96bc5d0c561A9)
 */
export function prepareWriteCounter<
  TAbi extends readonly unknown[] = typeof counterABI,
  TFunctionName extends string = string,
>(
  config: Omit<
    PrepareWriteContractConfig<TAbi, TFunctionName>,
    'abi' | 'address'
  > & { chainId?: keyof typeof counterAddress },
) {
  return prepareWriteContract({
    abi: counterABI,
    address: counterAddress[5],
    ...config,
  } as unknown as PrepareWriteContractConfig<TAbi, TFunctionName>)
}
